language: php
php:
  - hhvm
env:
  - DB_HOST=127.0.0.1:3307
before_install:
  - ./bin/db_local
  - ./bin/db_setup
  - composer config -g github-oauth.github.com 98cbc568911ef1e060a3a31623f2c80c1786d5ff
  - composer install
