cache:
  directories:
    - vendor
    - node_modules
    - bower_components

addons:
  mariadb: 10.0

language: php

php:
  - 5.6
  - 7.0
  - hhvm

env:
  - DB_USERNAME=root

before_install:
  - nvm install 4.2
  - nvm use 4.2
  - ./bin/db_setup
  - ./build.sh
